#version 450

layout(local_size_x = 256) in;

layout(set = 2, binding = 0, std430) writeonly buffer Heads
{
    uint uHeads[];
};

layout(set = 2, binding = 1, std430) writeonly buffer Counter
{
    uint uCounter;
};

layout(set = 0, binding = 0, std140) uniform Params
{
    vec4 uParams;
};

void main()
{
    uint id = gl_GlobalInvocationID.x;
    if (id < uint(uParams.x)) uHeads[id] = 0xFFFFFFFFu;
    if (id == 0u) uCounter = 0u;
}
