#!/usr/bin/env python3
"""Turns ltc.inc of https://github.com/selfshadow/ltc_code (fit/results/ltc.inc) into
common/LtcTables.h: per texel the inverse of the GGX LTC matrix reduced to its four free
entries, and the magnitude of the BRDF.

    gen_ltc_tables.py ltc.inc > common/LtcTables.h
"""
import re
import sys

src = open(sys.argv[1]).read()


def block(name):
    i = src.index(name)
    return src[i:src.index('};', i)]


def mats(name):
    return [[float(x) for x in m.group(1).split(',')]
            for m in re.finditer(r'\{([^{}]*)\}', block(name))]


b = block('tabMagnitude')
b = b[b.index('{') + 1:]
magnitude = [float(x.strip().rstrip('f')) for x in b.replace('\n', ' ').split(',') if x.strip()]
inverse = mats('tabMinv')
assert len(inverse) == 4096 and len(magnitude) == 4096


def fmt(x):
    return '%.7g' % x


LICENSE = '''// Copyright (c) 2017, Eric Heitz, Jonathan Dupuy, Stephen Hill and David Neubelt.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// * If you use (or adapt) the source code in your own work, please include a
//   reference to the paper:
//
//   Real-Time Polygonal-Light Shading with Linearly Transformed Cosines.
//   Eric Heitz, Jonathan Dupuy, Stephen Hill and David Neubelt.
//   ACM Transactions on Graphics (Proceedings of ACM SIGGRAPH 2016) 35(4), 2016.
//   Project page: https://eheitzresearch.wordpress.com/415-2/
//
// * Redistributions of source code must retain the above copyright notice, this
//   list of conditions and the following disclaimer.
//
// * Redistributions in binary form must reproduce the above copyright notice,
//   this list of conditions and the following disclaimer in the documentation
//   and/or other materials provided with the distribution.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

'''

print('''#pragma once

// Tables of linearly transformed cosines fitted to the GGX BRDF, 64 x 64 texels with the
// roughness (alpha = roughness^2) along x and sqrt(1 - cos(theta of the view)) along y.
//
// Generated by tools/gen_ltc_tables.py from fit/results/ltc.inc of
// https://github.com/selfshadow/ltc_code
//
@LICENSE@
namespace zenapp
{

namespace ltc
{

const unsigned kSize = 64;

// The inverse of the LTC matrix, scaled so that its middle entry is 1 (the scale does not change
// the directions it maps), as the vec4 (x, y, z, w) of the matrix
// mat3(vec3(x, 0, y), vec3(0, 1, 0), vec3(z, 0, w)) in the GLSL column order; one vec4 per texel.
const float kInverse[kSize * kSize * 4] = {'''.replace('@LICENSE@\n', LICENSE))
for i, m in enumerate(inverse):
    s = m[4]
    print('    ' + ', '.join(fmt(m[k] / s) for k in (0, 2, 6, 8)) + ',')
print('''};

// The integral of the BRDF times the cosine over the hemisphere, without Fresnel.
const float kMagnitude[kSize * kSize] = {''')
for i in range(0, 4096, 8):
    print('    ' + ', '.join(fmt(x) for x in magnitude[i:i + 8]) + ',')
print('''};

} // namespace ltc

} // namespace zenapp''')
